/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_Hello */

#ifndef _Included_JNI_Hello
#define _Included_JNI_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
